package DungeonMVC;

import java.awt.Image;
import java.awt.Rectangle;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 * Class to process and create the JPanels for the Hero, Enemy, and Chest
 * The door image requires separate processing due to unusual size and therefore not processed by this class.
 * 
 * @author Anton Thomas
 *
 */
public class DungeonChar {
	
	
	/**
	 * The Sprite attribute common to all elements generated by this class
	 */
	public JLabel Sprite;
	
	/**
	 * Takes a given image file taken from the images folder and creates a sized JPanel
	 * @param file
	 */
	public DungeonChar(ImageIcon file)
	{
		Image fileImage = file.getImage();
		Image newFileImg = fileImage.getScaledInstance((int) (1024 / 9.0), 250, java.awt.Image.SCALE_DEFAULT);
		file = new ImageIcon(newFileImg);
		this.Sprite = new JLabel(file);
	}
	
	/**
	 * Returns the bounding rectangle that contains the sprite on screen. Used for calculating placement on the screen as well as for collision detection
	 * @return Rectangle
	 */
	public Rectangle dimen(){
		
		return new Rectangle (Sprite.getX(), Sprite.getY(), Sprite.getWidth(), Sprite.getHeight());
	}
}
